services:
  mongodb:
    image: mongo:6.0
    container_name: iot_mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: iot_rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: iot_mqtt
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

volumes:
  mongo_data:
  rabbitmq_data:
  mosquitto_data:
  mosquitto_log: