services:
  iot_controller:
    image: iot_controller:${IMAGE_TAG}
    pull_policy: build
    build:
      context: ../..
      dockerfile: iot_controller/deploy/Dockerfile
    env_file:
      - iot_controller.env
    ports:
      - "${IOT_CONTROLLER_PORT}:8080"
    restart: unless-stopped
    networks:
      iot_net:
        aliases:
          - iot_controller
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        mode: "non-blocking"
        tag: "iot_controller"

networks:
  iot_net:
    external: true
    name: iot_net
