services:

  # INFRASTRUCTURE

  mongodb:
    image: mongo:8.2.3
    container_name: iot_mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      iot_net:
        aliases:
          - mongo

  rabbitmq:
    image: rabbitmq:4.2.2-management
    container_name: iot_rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      iot_net:
        aliases:
          - rabbitmq

  redis:
    image: redis:8.4.0
    container_name: iot_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      iot_net:
        aliases:
          - redis

  mosquitto:
    image: eclipse-mosquitto:2.0.22
    container_name: iot_mqtt
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ../config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      iot_net:
        aliases:
          - mosquitto
  
  # LOGS

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.3
    container_name: iot_elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      iot_net:
        aliases:
          - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:9.2.3
    container_name: iot_logstash
    volumes:
      - ../config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    ports:
      - "12201:12201/udp"
    depends_on:
      - elasticsearch
    networks:
      iot_net:
        aliases:
          - logstash

  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.3
    container_name: iot_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - iot_net

  # MONITORING

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: iot_redis_exporter
    environment:
      - REDIS_ADDR=redis://redis:6379
    networks:
      - iot_net

  mongo-exporter:
    image: percona/mongodb_exporter:0.47.2
    container_name: iot_mongo_exporter
    command:
      - '--mongodb.uri=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017'
    networks:
      - iot_net

  prometheus:
    image: prom/prometheus:latest
    container_name: iot_prometheus
    restart: always
    volumes:
      - ../config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      iot_net:
        aliases:
          - prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: iot_grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - iot_net
  
  # UTILS

  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_POLL_INTERVAL}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
    restart: unless-stopped
    networks:
      - iot_net
    profiles:
      - prod

volumes:
  mongo_data:
  rabbitmq_data:
  redis_data:
  mosquitto_data:
  mosquitto_log:
  grafana_data:
  elasticsearch_data:

networks:
  iot_net:
    name: iot_net
